# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image to be pushed to docker hub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      displayName: Running powershell to display various variables
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.          
          Write-Host "Build tag version is $(tag)"
    - task: Docker@2
      displayName: Build and Push the image to docker hub
      inputs:
        containerRegistry: 'vipindockerhubconnnection'
        repository: 'vipindocker1/myterraformwebapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
  
- stage: DeployTerraform
  displayName: Deploy terraform 
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy Terraform Job
    pool: ubuntu-latest
    variables: 
    - group: TeraformEnvVars
    steps:
    - script: |
        set e

        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: RunTerraform
      displayName: Run terraform apply script
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

    
