# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image to be pushed to docker hub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      displayName: Running powershell to display various variables
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.          
          Write-Host "Build tag version is $(tag)"
    - task: Docker@2
      displayName: Build and Push the image to docker hub
      inputs:
        containerRegistry: 'vipindockerhubconnnection'
        repository: 'vipindocker1/myterraformwebapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
